### ISSUE TITLE
Create New Tenant for Our Customer Seed of Hope

### ISSUE THREAD

**Issue by Tacchinardi20** [digi-serve/appbuilder_platform_service#88]
Seed of Hope is our customer for CARS App. They said that they have a data on their own site of our old version of Appbuilder. We are not sure what is their old url.

Please find their data, and move it to our current version of Appbuilder with have a CARS App.

The new url site for them should be https://seedofhope.childatrisk.in.th

Please Create User :
- Prin  Email :  prin@digiserve.org
Then I can create other users later.

You can use the same Site Administration and CARS data of ABDesigner from htttps://admin.childatrisk.in.th

**Comment by nh758** [comment]
Seed of hope is an fcf project. So data was in v1 cars.fcfthailand.org?

**Comment by wongpratan** [comment]
Yes, I think so.

I went to check `Children` data of `Seed of Hope`. There is 1 child.

I copied his/her info to the new `Seed of Hope` tenant already.
